#!/usr/bin/env bash
# Shared shell functions reused by apply.sh and pin-image.sh (ed25519 keygen / set_if_blank / toml rendering / misc).
# Not directly executable; source it.

rand() { openssl rand -hex "$1"; }

# sha256 of a file (openssl: same output on Linux and macOS, no sha256sum/shasum dependency).
file_sha256() { openssl dgst -sha256 "$1" | awk '{print $NF}'; }

# Reload .env (to pick up values freshly filled in by step scripts).
reload_env() { set -a; . ./.env; set +a; }

# Detect the host LAN IP (in local mode the S3 presigned endpoint must be a single address reachable by both the uploader and infra-service).
detect_lan_ip() {
  local ip=""
  if command -v ipconfig >/dev/null 2>&1; then
    ip="$(ipconfig getifaddr en0 2>/dev/null || true)"
    [ -z "$ip" ] && ip="$(ipconfig getifaddr en1 2>/dev/null || true)"
  fi
  if [ -z "$ip" ] && command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  [ -z "$ip" ] && ip="127.0.0.1"
  printf '%s' "$ip"
}

# set_if_blank KEY VALUE ENVFILE: if the line exists and is blank (KEY=), fill it in place; if the whole line is missing, append it; if already set, leave it untouched.
set_if_blank() {
  local key="$1" val="$2" envfile="$3"
  if grep -qE "^${key}=$" "$envfile"; then
    local tmp; tmp="$(mktemp)"
    while IFS= read -r line || [ -n "$line" ]; do
      if [ "$line" = "${key}=" ]; then printf '%s=%s\n' "$key" "$val"; else printf '%s\n' "$line"; fi
    done < "$envfile" > "$tmp"
    mv "$tmp" "$envfile"
    echo "[fill] ${key} (was blank -> generated)"
  elif ! grep -qE "^${key}=" "$envfile"; then
    printf '%s=%s\n' "$key" "$val" >> "$envfile"
    echo "[fill] ${key} (was missing -> appended)"
  fi
}

# set_kv KEY VALUE ENVFILE: force write (replace if present, append if missing). For derived values managed by apply (e.g. COMPOSE_FILE).
set_kv() {
  local key="$1" val="$2" envfile="$3"
  if grep -qE "^${key}=" "$envfile"; then
    local tmp; tmp="$(mktemp)"
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in "${key}="*) printf '%s=%s\n' "$key" "$val" ;; *) printf '%s\n' "$line" ;; esac
    done < "$envfile" > "$tmp"
    mv "$tmp" "$envfile"
  else
    printf '%s=%s\n' "$key" "$val" >> "$envfile"
  fi
}

# refresh_lan_ip KEY LAN_IP ENVFILE: on apply re-runs, refresh the "auto-managed LAN IP endpoints".
# If KEY's current value looks like http://<ipv4>:<port> and the ipv4 differs from the current LAN_IP, replace the ipv4 with LAN_IP in place (port preserved).
# minio:9000 / hostnames / unchanged values are left as-is; skip when LAN_IP detection failed (empty or 127.0.0.1) to avoid clobbering a usable IP with loopback.
refresh_lan_ip() {
  local key="$1" lan_ip="$2" envfile="$3"
  [ -n "$lan_ip" ] && [ "$lan_ip" != "127.0.0.1" ] || return 0
  local cur; cur="$(grep -E "^${key}=" "$envfile" | head -1 | cut -d= -f2-)"
  printf '%s' "$cur" | grep -qE '^http://[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+$' || return 0
  local cur_ip; cur_ip="$(printf '%s' "$cur" | sed -E 's#^http://([0-9.]+):.*#\1#')"
  [ "$cur_ip" != "$lan_ip" ] || return 0
  local newv; newv="$(printf '%s' "$cur" | sed -E "s#^http://[0-9.]+:#http://${lan_ip}:#")"
  local tmp; tmp="$(mktemp)"
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "${key}=${cur}" ]; then printf '%s=%s\n' "$key" "$newv"; else printf '%s\n' "$line"; fi
  done < "$envfile" > "$tmp"
  mv "$tmp" "$envfile"
  echo "[update] ${key}: ${cur} -> ${newv} (LAN IP changed)"
}

# ed25519 keypair: prefer openssl (Linux OpenSSL); macOS LibreSSL lacks support, so fall back to a node:22-slim container.
# Output: private key PEM + "---SPLIT---" + public key PEM.
ed25519_pair() {
  local p s
  p="$(mktemp)"; s="$(mktemp)"
  if openssl genpkey -algorithm ed25519 -out "$p" 2>/dev/null \
     && openssl pkey -in "$p" -pubout -out "$s" 2>/dev/null; then
    cat "$p"; echo "---SPLIT---"; cat "$s"; rm -f "$p" "$s"; return 0
  fi
  rm -f "$p" "$s"
  if command -v docker >/dev/null 2>&1; then
    docker run --rm node:22-slim node -e 'const c=require("crypto");const{publicKey,privateKey}=c.generateKeyPairSync("ed25519");process.stdout.write(privateKey.export({type:"pkcs8",format:"pem"})+"---SPLIT---\n"+publicKey.export({type:"spki",format:"pem"}))' 2>/dev/null && return 0
  fi
  return 1
}

# Write docker-compose.override.yml (git multi-line PEMs). Args: OVERRIDE PRIV_PEM PUB_PEM.
write_git_override() {
  local override="$1" priv="$2" pub="$3"
  {
    echo "# Generated by apply.sh: multi-line PEMs are injected via this override (.env cannot hold multi-line values). Do not commit."
    echo "services:"
    echo "  infra-service:"
    echo "    environment:"
    echo "      GIT_REGISTRY_JWT_PRIVATE_KEY: |"
    printf '%s\n' "$priv" | sed '/^[[:space:]]*$/d; s/^/        /'
    echo "  git-registry:"
    echo "    environment:"
    echo "      GIT_REGISTRY_JWT_PUBLIC_KEY: |"
    printf '%s\n' "$pub" | sed '/^[[:space:]]*$/d; s/^/        /'
  } > "$override"
}

# Escape a value for use as a sed `s|...|VALUE|` replacement: `\`, `&` (= matched text) and the `|` delimiter.
sed_escape() { printf '%s' "$1" | sed -e 's/[\\&|]/\\&/g'; }

# Reject characters that cannot be carried inside a TOML basic string without escaping (`"` and `\`) or that
# would break the line ($'\n'). Args: LABEL VALUE. Paths with `&`, `|`, spaces and unicode are fine.
require_toml_safe() {
  case "$2" in
    *'"'*|*'\'*|*$'\n'*) echo "[x] $1 must not contain double quotes, backslashes or newlines: $2"; exit 1 ;;
  esac
}

# Render opensandbox.generated.toml (injects execd/egress image refs + sandbox network name; api_key is not set here, compose env injects it).
# Args: EXECD_IMAGE EGRESS_IMAGE SANDBOX_NET [CA_BINDS_LINE] [CA_ENV_LINE] -- the last two are whole
# TOML lines (or empty) built by apply.d/40-runtime.sh from PRIVATE_CA_FILE / SANDBOX_EXTRA_BINDS / SANDBOX_TLS_NO_VERIFY.
# Values are sed-escaped (a `&` or `|` in a path must not corrupt the file) and the output is written to a
# temp file first, so a failed render leaves the previous generated config in place.
render_toml() {
  local execd_image="$1" egress_image="$2" sandbox_net="$3" ca_binds_line="${4:-}" ca_env_line="${5:-}"
  [ -f opensandbox.toml ] || { echo "[!] opensandbox.toml template missing, skipping render"; return 0; }
  local before=""; [ -f opensandbox.generated.toml ] && before="$(cksum < opensandbox.generated.toml)"
  local tmp; tmp="$(mktemp)"
  if ! sed -e "s|__EXECD_IMAGE__|$(sed_escape "${execd_image}")|g" \
           -e "s|__EGRESS_IMAGE__|$(sed_escape "${egress_image}")|g" \
           -e "s|__SANDBOX_NETWORK__|$(sed_escape "${sandbox_net}")|g" \
           -e "s|__SANDBOX_CA_BINDS__|$(sed_escape "${ca_binds_line}")|" \
           -e "s|__SANDBOX_CA_ENV__|$(sed_escape "${ca_env_line}")|" \
           opensandbox.toml > "$tmp"; then
    rm -f "$tmp"; echo "[x] rendering opensandbox.generated.toml failed; previous file left untouched"; exit 1
  fi
  if grep -q "__SANDBOX_CA_BINDS__\|__SANDBOX_CA_ENV__\|__EXECD_IMAGE__\|__EGRESS_IMAGE__\|__SANDBOX_NETWORK__" "$tmp"; then
    rm -f "$tmp"; echo "[x] rendering opensandbox.generated.toml left a placeholder behind; previous file left untouched"; exit 1
  fi
  mv "$tmp" opensandbox.generated.toml
  echo "[ok] opensandbox.generated.toml"
  # The engine reads this file once at start. 40-runtime records its fingerprint in .env and compose carries
  # it as an environment variable, so a changed file changes the service definition and a plain
  # `docker compose up -d` recreates the engine -- say so whenever the rendered config changed.
  if [ -n "$before" ] && [ "$before" != "$(cksum < opensandbox.generated.toml)" ]; then
    echo "[~] opensandbox.generated.toml changed: docker compose up -d recreates opensandbox-server (new sandboxes pick it up)"
  fi
}

# Render a server Caddyfile template: __TLS_GLOBAL__ (whole line -> the global options block, or nothing)
# and __TLS_SITE__ (inline -> the per-site tls directive, or nothing). Args: TEMPLATE OUTPUT TLS_GLOBAL TLS_SITE.
# The {$VAR} placeholders stay literal: caddy expands them from the container environment at parse time.
render_caddyfile() {
  local tpl="$1" out="$2"
  [ -f "$tpl" ] || { echo "[x] $tpl missing"; exit 1; }
  TLS_GLOBAL="$3" TLS_SITE="$4" awk '
    /^__TLS_GLOBAL__$/ { printf "%s", ENVIRON["TLS_GLOBAL"]; next }
    { while ((i = index($0, "__TLS_SITE__")) > 0) $0 = substr($0, 1, i - 1) ENVIRON["TLS_SITE"] substr($0, i + 12) }  # literal splice (gsub would expand &)
    { print }
  ' "$tpl" > "$out"
  echo "[ok] $out"
}
