# Copyright 2026 Alibaba Group Holding Ltd.
# Gateway RBAC: ServiceAccount, ClusterRole, ClusterRoleBinding (read-only sandbox discovery).
{{- if and .Values.server.gateway.enabled (.Values.server.gateway.rbac).create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opensandbox-server.ingressGatewayFullname" . }}
  namespace: {{ include "opensandbox-server.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "opensandbox-server.ingressGatewayFullname" . }}
    app.kubernetes.io/part-of: opensandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opensandbox-server.ingressGatewayFullname" . }}-reader-full
  labels:
    app.kubernetes.io/name: {{ include "opensandbox-server.ingressGatewayFullname" . }}
    app.kubernetes.io/part-of: opensandbox
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["sandbox.opensandbox.io"]
    resources: ["batchsandboxes", "batchsandboxes/status"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "opensandbox-server.ingressGatewayFullname" . }}-reader-full
  labels:
    app.kubernetes.io/name: {{ include "opensandbox-server.ingressGatewayFullname" . }}
    app.kubernetes.io/part-of: opensandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "opensandbox-server.ingressGatewayFullname" . }}-reader-full
subjects:
  - kind: ServiceAccount
    name: {{ include "opensandbox-server.ingressGatewayFullname" . }}
    namespace: {{ include "opensandbox-server.namespace" . }}
{{- end }}
